version: '3.1'

services:
  postgre_db:
    image: postgres:15
    container_name: postgre_vroum
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: VROUM
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - myapp_network

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  myapp_network:
